eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3MTgwNTY5MDZ9.sJpRp3vhQIUW3u_FYvk5qkRJ2KfqGycuzPngJ7L_Xo8:
  id: 1
  role: Head Doctor
  username: Fairouz Hamdy
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3MTgwNTc3NTl9.DYrzBjiqIlJA4fRv31rFxyzW2u37mrmcoUW7CdVZFNg:
  id: 1
  role: Head Doctor
  username: Fairouz Hamdy
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE3MTgwNTg0NjZ9.27uxfvvWNa_jxg1Co-T_gPoKu0mAUuqLvMlNuqfHmAE:
  id: 1
  role: Admin
  username: Mona Elbatran
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MTgwNTY1NzV9.dLvgqUyfR4p5v4uMW1UJ1xHoOud20NUzL01W1tUEh5E:
  id: 2
  role: Data Analyst
  username: Bella Hadid
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MTgwNTc3MjR9.ZenWsA4gGGpOz5V9r1tpk8FJCgzK2M9CiX61zA7N1tw:
  id: 2
  role: Data Analyst
  username: Bella Hadid
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MTgwNTg1MDV9.WBZcNwJz--EEcHeE1SYFnYLHLA0LhRb1hw9zUdAsvzo:
  id: 2
  role: Data Analyst
  username: Bella Hadid
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3MTgwNTkxOTV9.QryiB_QkdfMXn-4uCbQ4W4NeCrGhSGiUGsmXeczd8i0:
  id: 2
  role: Data Analyst
  username: Bella Hadid
? eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMiwiZXhwIjoxNzE4MDU2MTAyfQ.QGtVTE3O3_HRuaKqATlPAsIn0GsSV8OgR7gwCssE8mU
: id: 22
  role: Physician
  username: Mohra Ayman
? eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMiwiZXhwIjoxNzE4MDU2NDgzfQ.Hts5kKGIcQR9LTK2ZGwwbpBcEXFXD9JzJr1cjMXT9-M
: id: 22
  role: Physician
  username: Mohra Ayman
? eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMiwiZXhwIjoxNzE4MDU3Njk3fQ.fZH96o4vGeNIKiYN42jH5ufMSpqecmUFkebYonIvMkU
: id: 22
  role: Physician
  username: Mohra Ayman
? eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMiwiZXhwIjoxNzE4MDU5MDUyfQ.Nj12IVZlbkkC0FP35KlNS8DP_zwbwK7TTXum66NFDtY
: id: 22
  role: Physician
  username: Mohra Ayman
