# Generated by Django 5.0.4 on 2024-05-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_doctor_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_info', models.JSONField(default=dict)),
                ('MRN', models.BigIntegerField()),
                ('doctors', models.ManyToManyField(blank=True, to='doctors.doctor')),
            ],
        ),
    ]
