# Generated by Django 5.0.4 on 2024-05-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Filled'), (2, 'Approved by engineer'), (3, '\u2060Ground truth added'), (4, '\u2060Reviewd'), (5, '\u2060Retrianed')], default=1),
            preserve_default=False,
        ),
    ]
