# Generated by Django 5.0.4 on 2024-05-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_ground_truth_alter_assessment_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
