# Generated by Django 5.0.4 on 2024-05-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Filled'), (2, 'Approved by engineer'), (3, '\u2060Ground truth added'), (4, '\u2060Reviewd'), (5, '\u2060Retrianed')], null=True),
        ),
    ]
