# Generated by Django 5.0.4 on 2024-05-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_assessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Filled'), (2, '\u2060Ground truth added'), (3, '\u2060Reviewd'), (4, '\u2060Retrianed')], null=True),
        ),
    ]
