# Generated by Django 5.0.4 on 2024-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='firstName',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastName',
            field=models.CharField(max_length=250),
        ),
    ]
