# Generated by Django 5.0.4 on 2024-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_firstname_alter_doctor_lastname'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='patients.patient'),
        ),
    ]
