# Generated by Django 5.0.4 on 2024-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('doctors', '0003_doctor_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='assessments',
            field=models.ManyToManyField(to='assessments.assessment'),
        ),
    ]
