# Generated by Django 5.0.4 on 2024-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='firstName',
            field=models.CharField(default='Ahmed', max_length=250),
        ),
        migrations.AddField(
            model_name='admin',
            name='lastName',
            field=models.CharField(default='Ezz', max_length=250),
        ),
    ]
