# Generated by Django 5.0.6 on 2024-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='headDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('firstName', models.CharField(default='Ahmed', max_length=250)),
                ('lastName', models.CharField(default='Ezz', max_length=250)),
            ],
        ),
    ]
